# Generated by Django 5.0.4 on 2026-04-21 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawmatch_api', '0003_remove_reminder_pet_delete_healthrecord_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pawmatch_api.animal', unique=True),
        ),
    ]
